// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RelojCatReloj
    {
        public int ClaReloj { get; set; }
        public int ClaEmpresa { get; set; }
        public int? ClaGrupoReloj { get; set; }
        public string NomReloj { get; set; }
        public bool Estatus { get; set; }
        public string DireccionIp { get; set; }
        public int? TipoEntsal { get; set; }
        public bool? Protegido { get; set; }
        public int? ClaUbicacion { get; set; }
    }
}