// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace biz.rebel_wings.Entities
{
    public partial class _25pts
    {
        public int Id { get; set; }
        public DateTime FechaIni { get; set; }
        public int Sala { get; set; }
        public int Mesa { get; set; }
        public int TotalAyc { get; set; }
        public int Cobros { get; set; }
        public int CobrosMinimos { get; set; }
        public int Diferencia { get; set; }
        public string Justificacion { get; set; } = null!;
        public string Usuario { get; set; } = null!;
        public string Sucursal { get; set; } = null!;


    }
}
