// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace biz.rebel_wings.Entities
{
    public partial class InventarioMensualRegistro
    {
        public int? Id { get; set; }
        public int City { get; set; }
        public int Sucursal { get; set; }
        public string Captura { get; set; } = null!;
        public DateTime DateCaptura { get; set; }
        public bool Procesado { get; set; }
    }
}
