// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace biz.bd2.Entities
{
    public partial class ReporteV
    {
        public string cod { get; set; }
        public string Sucursal { get; set; }
        public string Articulo { get; set; }
        public string InvAyer { get; set; }
        public double TraspasoAyer { get; set; }
        public double ConsumoAyer { get; set; }
        public string InvHoy { get; set; }
        public double InvFormula { get; set; }
        public double Diferencia { get; set; }
        public DateTime Captura { get; set; }
        public string Seccion { get; set; }
    }
}
